/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './cache.module';
class CacheModuleInjector extends import0.ɵNgModuleInjector<import1.CacheModule> {
  _CacheModule_0:import1.CacheModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.CacheModule {
    this._CacheModule_0 = new import1.CacheModule();
    return this._CacheModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.CacheModule)) { return this._CacheModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CacheModuleNgFactory:import0.NgModuleFactory<import1.CacheModule> = new import0.NgModuleFactory<any>(CacheModuleInjector,import1.CacheModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhdmUvRGV2ZWxvcG1lbnQvaW9uaWMtY2FjaGUvc3JjL2NhY2hlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9kYXZlL0RldmVsb3BtZW50L2lvbmljLWNhY2hlL3NyYy9jYWNoZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
